[workspace]
members = [
  "crates/better-wallpaper-core",
  "crates/better-wallpaper-daemon",
  "crates/better-wallpaper-ffmpeg",
  "crates/better-wallpaper-kde",
  "crates/better-wallpaper-renderer",
  "crates/better-wallpaper-scene-format",
  "crates/better-wallpaper-wayland",
  "crates/gpu-renderer",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
ash = { version = "0.37.3", default-features = false, features = ["loaded"] }
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
ffmpeg-next = "8.0"
glow = "0.13"
khronos-egl = { version = "6.0", features = ["dynamic", "1_4"] }
memmap2 = "0.9"
ksni = { version = "0.3.5", features = ["blocking"] }
rodio = { version = "0.21.1", default-features = false, features = ["playback"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
tempfile = "3.20"
tiny_http = "0.12"
thiserror = "2.0"
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
smithay-client-toolkit = { version = "0.19.2", default-features = false }
wayland-client = "0.31.12"
wayland-backend = { version = "0.3.12", features = ["client_system"] }
zerocopy = "0.8"
