[package]
name = "better-wallpaper-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
better-wallpaper-scene-format = { path = "../better-wallpaper-scene-format" }
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

