[package]
name = "gpu-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
glow.workspace = true
better-wallpaper-core = { path = "../better-wallpaper-core" }
better-wallpaper-renderer = { path = "../better-wallpaper-renderer" }
better-wallpaper-scene-format = { path = "../better-wallpaper-scene-format" }
better-wallpaper-ffmpeg = { path = "../better-wallpaper-ffmpeg" }
half = "2"
tracing.workspace = true
