[package]
name = "better-wallpaper-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ash.workspace = true
better-wallpaper-scene-format = { path = "../better-wallpaper-scene-format" }
fontdue.workspace = true
thiserror.workspace = true
tracing.workspace = true
