cmake_minimum_required(VERSION 3.20)
project(better-wallpaper-web LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(Qt6 6.6 REQUIRED COMPONENTS Quick WebEngineQuick)
find_package(LayerShellQt REQUIRED)
qt_add_executable(better-wallpaper-web main.cpp)
qt_add_resources(better-wallpaper-web "wallpaper" PREFIX "/" FILES WebWallpaper.qml)
target_link_libraries(better-wallpaper-web PRIVATE Qt6::Quick Qt6::WebEngineQuick LayerShellQt::Interface)
target_compile_options(better-wallpaper-web PRIVATE -Wall -Wextra -Werror)
